DROP DATABASE IF EXISTS movie_database;
CREATE DATABASE movie_database; 
USE movie_database;

DROP TABLE IF EXISTS theatre1;

CREATE TABLE theatre1 (
  `movie_name` VARCHAR(50) CHARACTER SET 'ascii' NOT NULL COMMENT 'name of movie',
  `time` DATETIME NOT NULL COMMENT 'date and time of movie showing',
  `seat1` TINYINT(1) NOT NULL DEFAULT 1,
  `seat2` TINYINT(1) NOT NULL DEFAULT 1,
  `seat3` TINYINT(1) NOT NULL DEFAULT 1,
  `seat4` TINYINT(1) NOT NULL DEFAULT 1,
  `seat5` TINYINT(1) NOT NULL DEFAULT 1,
  `seat6` TINYINT(1) NOT NULL DEFAULT 1,
  `seat7` TINYINT(1) NOT NULL DEFAULT 1,
  `seat8` TINYINT(1) NOT NULL DEFAULT 1,
  `seat9` TINYINT(1) NOT NULL DEFAULT 1,
  `seat10` TINYINT(1) NOT NULL DEFAULT 1,
  `seat11` TINYINT(1) NOT NULL DEFAULT 1,
  `seat12` TINYINT(1) NOT NULL DEFAULT 1,
  `seat13` TINYINT(1) NOT NULL DEFAULT 1,
  `seat14` TINYINT(1) NOT NULL DEFAULT 1,
  `seat15` TINYINT(1) NOT NULL DEFAULT 1,
  `seat16` TINYINT(1) NOT NULL DEFAULT 1,
  `seat17` TINYINT(1) NOT NULL DEFAULT 1,
  `seat18` TINYINT(1) NOT NULL DEFAULT 1,
  `seat19` TINYINT(1) NOT NULL DEFAULT 1,
  `seat20` TINYINT(1) NOT NULL DEFAULT 1);